spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zycon/spring-cloud-config
          search-paths: hawk-config
          clone-on-start: true
  application:
    name: hawk-server
server:
  port: 8888